
  development:
    adapter: mysql
    database: default_db
    username: rafal_slabon
    password: ZXCVbnm,1
    host: ec2-50-19-213-178.compute-1.amazonaws.com

  test:
    adapter: mysql
    database: default_db
    username: rafal_slabon
    password: ZXCVbnm,1
    host: ec2-50-19-213-178.compute-1.amazonaws.com

  production:
    adapter: mysql
    database: default_db
    username: rafal_slabon
    password: ZXCVbnm,1
    host: ec2-50-19-213-178.compute-1.amazonaws.com
